apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-flux
  namespace: default
spec:
  releaseName: nginx-flux
  targetNamespace: default
  rollback:
    enable: flase
  test:
    enable: true
    ignoreFailures: true
  chart:
    git: git@github.com:sureshpalemoni/flux-test.git
    path: charts/nginx
    ref: master
  values:
    image:
      tag: 1.19.7-debian-10-r6
    replicaCount: 1
