apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-flux
  namespace: default
spec:
  releaseName: nginx-flux
  targetNamespace: default
  chart:
    git: git@github.com:sureshpalemoni/flux-test.git
    path: charts/nginx
    ref: master
  values:
    tag: 1.19.7-debian-10-r7
